/*
 * @author 鼓捣JIA
 * @date 2024/2/23 12:47
 */

import { PagesPathModel } from '../common/PagesPathModel'

const dialog: Array<PagesPathModel> = [
  { name: 'AlertDialog 警告弹窗',
    address: 'pages/dialog/AlertDialogPage' },

  { name: 'ActionSheet 列表选择弹窗',
    address: 'pages/dialog/ActionSheetPage' },

  { name: 'CustomDialog 自定义弹窗',
    address: 'pages/dialog/CustomDialogPage' },

  { name: 'DatePickerDialog 日期选择弹窗',
    address: 'pages/dialog/DatePickerDialogPage' },

  { name: 'TimePickerDialog 时间选择弹窗',
    address: 'pages/dialog/TimePickerDialogPage' },

  { name: 'TextPickerDialog 文本选择弹窗',
    address: 'pages/dialog/TextPickerDialogPage' },
]

export default dialog